### ISSUE TITLE
Compare sample data in BAM/FASTQ format against a reference FASTA ?

### ISSUE THREAD

**Issue by biocyberman** [sauloal/cnidaria#1]
Hi
I have a fasta file containing a thousand virus sequences of the same species. I also have a unaligned BAM file which can be easily converted to FASTQ file. Can I use the BAM/FASTQ file and cluster the sample therein with the reference database in the FASTA file?

My goal is to find the closest match to the sample I am testing.

**Comment by sauloal** [comment]
Hello @biocyberman . sorry for the delay. haven't checked this page in a while.
FastQ files can be used as Jellyfish can read them. no problem.
I've never tested this software with viruses though.

**Comment by vikramnarke18** [comment]
input send though inner type of vector :-
{5,6,7,8}
{45,36,42,159}

Expected output:-{"final output":[[1,2,3,4],[5,6,4,1]]}

//inner vector is of type int (const std::vector <int>inner)





std::string fun( const std::vector< inner >& outer ) {
    rapidjson::Value array( rapidjson::kArrayType );
    rapidjson::Document Document1;
    Document1.SetObject();
    auto& alloc = Document1.GetAllocator();
	for( auto inner : outer)
	{
		array.PushBack( inner, alloc);
	}

    Document1.AddMember( "final output", array, alloc );
    rapidjson::StringBuffer buffer;
    buffer.Clear();
    rapidjson::Writer< rapidjson::StringBuffer > writer( buffer );
    Document.Accept( writer );
    return std::string( buffer.GetString() );
	
	
I am facing error .Please suggest solution

**Comment by sauloal** [comment]
@vikramnarke18 . I have not idea what you're talking about . and this is not related to the issue at hand. please open a new issue and explain the problem better.
regards
